[env:scanner]
platform  = espressif32
board     = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed  = 921600
board_build.filesystem = littlefs
board_build.partitions = partitions.csv

build_flags =
    -D CORE_DEBUG_LEVEL=3

lib_deps =
    h2zero/NimBLE-Arduino @ ^1.4.1
    miguelbalboa/MFRC522 @ ^1.4.11
    makuna/RTC @ ^2.5.0
    bblanchon/ArduinoJson @ ^7.0.4
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
    tzapu/WiFiManager @ ^2.0.17
