[env:scanner]
platform  = espressif32
board     = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed  = 921600
board_build.filesystem = littlefs

build_flags =
    -D CORE_DEBUG_LEVEL=3

lib_deps =
    miguelbalboa/MFRC522 @ ^1.4.11
    adafruit/RTClib @ ^2.1.4
    bblanchon/ArduinoJson @ ^7.0.4
